[tool.poetry]
name = "lep-downloader"
version = "3.0.0b3"
description = "LEP Downloader - CLI app for parsing and downloading episodes of Luke's English Podcast"
authors = ["Artem Hotenov <qa@hotenov.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/hotenov/LEP-downloader"
repository = "https://github.com/hotenov/LEP-downloader"
documentation = "https://lep-downloader.readthedocs.io"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.urls]
Changelog = "https://github.com/hotenov/LEP-downloader/releases"


[tool.poetry.dependencies]
python = "^3.8.0"
click = "^8.0.4"
requests = "^2.26.0"
beautifulsoup4 = "^4.9.3"
lxml = "^4.9.1"
single-source = "^0.2.0"
loguru = "^0.6.0"

[tool.poetry.group.test.dependencies]
pytest = "^6.2.5"
pytest-mock = "^3.6.1"
requests-mock = "^1.9.3"
safety = "^2.2.0"
coverage = {extras = ["toml"], version = "^6.1"}
typeguard = "^2.13.3"
xdoctest = {extras = ["colors"], version = "^0.15.10"}

[tool.poetry.group.lint.dependencies]
flake8 = "^4.0.1"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^21.9.2"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
flake8-black = "^0.2.3"
flake8-import-order = "^0.18.1"
mypy = "^0.910"
darglint = "^1.8.1"
pep8-naming = "^0.12.1"

[tool.poetry.group.format.dependencies]
black = ">=21.10b0"
yapf = "^0.31.0"
pre-commit = "^2.15.0"
pre-commit-hooks = "^4.0.1"
reorder-python-imports = "^2.6.0"
rope = "^0.20.1"

[tool.poetry.group.docs.dependencies]
sphinx = "^4.3.0"
sphinx-autobuild = ">=2021.3.14"
sphinx-click = "^3.0.2"
Pygments = "^2.10.0"
furo = ">=2022.2.23"

[tool.poetry.group.dev.dependencies]


[tool.poetry.scripts]
lep-downloader = "lep_downloader.__main__:main"
lep-dl = "lep_downloader.__main__:main"


[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["lep_downloader"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = [
    "lep_downloader.commands.makepdf",
    "lep_downloader.commands.utils",
]
ignore_errors = true

[[tool.mypy.overrides]]
module = [
    'desert',
    'pytest',
    'pytest_mock.*',
    'requests.*',
    'bs4.*',
    'requests_mock.*',
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
force_single_line = true
force_sort_within_sections = false
lexicographical = true
order_by_type = false
group_by_package = true
src_paths = ["src", "tests"]
lines_after_imports = 2
